title: Social network of Hogwarts
description: A short description of your site's purpose
show_downloads: false

repository: thomasoerkild.github.io/TheSocialNetworkOfHogwarts

theme: jekyll-theme-midnight

